### ISSUE TITLE
Mail MarkAsRead/MarkAllAsRead/MarkAsUnread problematic in webmail lite and webmail pro

### ISSUE THREAD

**Issue by rapsys** [afterlogic/aurora-module-webclient-mail#8]
I tested with webmail lite version 8.5.3 and webmail pro version 8.3.16 and I get the same problem about read button.

When I select an already readed message the button remain set to MarkAsRead, the first contextual choice is MarkAllAsRead and only then MarkAsUnread.

It would be nice to have the button changed dynamicaly based on the message read status.

Button MarkAsRead with an unread message in the selection.
Button MarkAsUnread with only read message in the selection.

For me it's the most problematic missing feature of the webmail.

It would be nice as well that the MarkAllAsRead be with a contextual confirmation, I lost all my message read status while trying to set as unread one message, very anoying...

Best regards

**Comment by afterlogic-support** [comment]
Please feel free to post a feature suggestion at:
https://afterlogic.uservoice.com/forums/932335-webmail-pro
We use that resource when developing product's roadmap, so if the feature gets a good number of votes, there's a better chance of it getting implemented. Thanks.
