### ISSUE TITLE
Module config.json not copied in data

### ISSUE THREAD

**Issue by rapsys** [afterlogic/aurora-module-webclient-mail#9]
I installed the module with the pro procedure.

But the module config don't get copied from modules/MailWebclient/config.json to data/settings/modules/MailWebclient.config.json

I found this problem while trying to enable the Horizontal layout.

Best regards

**Comment by rapsys** [comment]
With webmail pro version 8.3.16

**Comment by afterlogic-support** [comment]
That's a very old version, the issue should be corrected in the current 9.6.1.
